name: flutter_image_compress
description: Compress image with native (Objective-C/Kotlin) with faster speed. Support Android/iOS.
repository: https://github.com/fluttercandies/flutter_image_compress
version: 1.1.3

environment:
  sdk: '>=2.8.0 <3.0.0'
  flutter: '>=1.6.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttercandies.flutter_image_compress
        pluginClass: ImageCompressPlugin
      ios:
        pluginClass: ImageCompressPlugin
